{% set name = "epispot" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/epispot/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b1116e860dd52aedffd900bf958952eef2182331b9ec7fc1288e5fffdfb3c7e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  imports:
    - epispot

about:
  home: https://github.com/epispot/epispot
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A tool for modeling infectious diseases.

extra:
  recipe-maintainers:
    - Quantalabs
